version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-03T17-50-39Z
    command: ["server", "/data", "--console-address", ":9001"]

    # Expose the ports
    ports:
      - "9000:9000"
      - "9001:9001"

    # Define the environment variables in the .env file
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
    restart: on-failure

  minio-create-bucket:
    image: minio/mc
    volumes:
      - './.docker/minio:/etc/minio'
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    depends_on:
      - minio
    entrypoint: /etc/minio/create-buckets.sh
    restart: "no"

volumes:
  minio_data: